#!/bin/sh

# PROVIDE: Sficoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# Sficoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable Sficoin service.
# Sficoin_config (path): Set to /usr/local/etc/Sficoin.conf by default.
# Sficoin_user:  The user account Sficoin daemon runs as. It uses 'root' user by default.
# Sficoin_group: The group account Sficoin daemon runs as. It uses 'wheel' group by default.
# Sficoin_datadir (str): Default to "/var/db/Sficoin". Base data directory.

. /etc/rc.subr

name=Sficoin
rcvar=Sficoin_enable

: ${Sficoin_enable:=NO}
: ${Sficoin_config=/usr/local/etc/Sficoin.conf}
: ${Sficoin_datadir=/var/db/Sficoin}
: ${Sficoin_user="root"}
: ${Sficoin_group="wheel"}

required_files=${Sficoin_config}
command=/usr/local/bin/Sficoind
Sficoin_chdir=${Sficoin_datadir}
pidfile="${Sficoin_datadir}/Sficoind.pid"
stop_cmd=Sficoin_stop
command_args="-conf=${Sficoin_config} -datadir=${Sficoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

Sficoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${Sficoin_datadir}
	[ $? -eq 0 ] && chown -R ${Sficoin_user}:${Sficoin_group} ${Sficoin_datadir}
}

Sficoin_prestart()
{
	if [ ! -d "${Sficoin_datadir}/." ]; then
		Sficoin_create_datadir || return 1
	fi
}

Sficoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

Sficoin_stop()
{
    Sficoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${Sficoin_config} -datadir=${Sficoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
